# Generated by Django 3.2.3 on 2023-10-19 07:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
